name: Deploy Next.js App to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # disable the Next.js telemetry prompt
      NEXT_TELEMETRY_DISABLED: '1'

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cache node_modules
      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 3. Cache Next.js build cache
      - name: Cache Next.js build cache
        uses: actions/cache@v3
        with:
          # Next.js writes caching data here
          path: .next/cache
          key: ${{ runner.os }}-next-cache-${{ hashFiles('**/package-lock.json','next.config.js') }}
          restore-keys: |
            ${{ runner.os }}-next-cache-

      # 4. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 5. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 6. Build your Next.js app
      - name: Build production bundle
        run: npm run build

      # 7. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v12.9.0
        with:
          args: deploy --only hosting --project fir-rbac-app

        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

